# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VsZCzJYEB7O8n68NB3Wf-R7aF1-ss0d
"""

!pip install tensorflow opencv-python-headless matplotlib

!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!pip install -r requirements.txt

from google.colab import files
uploaded = files.upload()

# Display the uploaded image
import cv2
import matplotlib.pyplot as plt

for filename in uploaded.keys():
    image = cv2.imread(filename)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

!python detect.py --source "Annotation 2021-10-24 121647 (2).png" --weights yolov5s.pt --conf 0.5

import os

# List files in the output directory
output_dir = "runs/detect"
for root, dirs, files in os.walk(output_dir):
    for file in files:
        print(os.path.join(root, file))

output_file ="runs/detect/exp/Annotation 2021-10-24 121647 (2).png"

from google.colab import files
files.download(output_file)

from google.colab import files
uploaded = files.upload()

# Display the uploaded image
import cv2
import matplotlib.pyplot as plt

for filename in uploaded.keys():
    image = cv2.imread(filename)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

!python detect.py --source "f.png" --weights yolov5s.pt --conf 0.5

!python detect.py --source f.png --weights yolov5m.pt --conf 0.3

!wget https://github.com/ultralytics/yolov5/releases/download/v1.0/bus.jpg -O test_image.jpg

!python detect.py --source test_image.jpg --weights yolov5s.pt --conf 0.3

from google.colab import files

# Specify the path to the output image
result_image_path = 'runs/detect/exp6/test_image.jpg'

# Download the result
files.download(result_image_path)



!wget https://storage.googleapis.com/openimages/web/download.html -O test_video.mp4

!ffmpeg -i test_video.mp4 -c:v libx264 -preset fast -crf 22 -c:a aac -b:a 192k -strict experimental test_video_reencoded.mp4



from google.colab import files

# Upload a video file
uploaded = files.upload()

!python detect.py --source test.mp4 --weights yolov5s.pt --conf 0.3 --save-txt --save-crop --project runs/detect --name exp_video

from IPython.display import Video
Video("runs/detect/exp_video2/test.mp4")

import shutil
shutil.move('runs/detect/exp_video2/test.mp4', '/content/test_video_processed.mp4')

from google.colab import files
files.download('/content/test_video_processed.mp4')

from IPython.display import Image, display

# Display the output image
display(Image(filename="runs/detect/exp6/test_image.jpg"))

!wget https://github.com/ultralytics/yolov5/releases/download/v1.0/bus.jpg -O test_image.jpg

!python detect.py --source test_image.jpg --weights yolov5s.pt --conf 0.3

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!git clone https://github.com/ultralytics/yolov5.git

!pip install -U ultralytics

